### ISSUE TITLE
Babel error starting web platform for blank template

### ISSUE THREAD

**Issue by cereigido** [pavjacko/renative#473]
On a new project based on blank template, web server would not start with error below:

```
ERROR in ./src/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/xxx/Documents/workspace/xxx/src/app.js: Could not find plugin "proposal-numeric-separator". Ensure there is an entry in ./available-plugins.js for it. (While processing: "/Users/xxx/Documents/workspace/xxx/node_modules/@babel/preset-env/lib/index.js")
    at getPlugin (/Users/xxx/Documents/workspace/xxx/node_modules/@babel/preset-env/lib/index.js:67:11)
    at /Users/xxx/Documents/workspace/xxx/node_modules/@babel/preset-env/lib/index.js:258:62
    at Array.map (<anonymous>)
    at /Users/xxx/Documents/workspace/xxx/node_modules/@babel/preset-env/lib/index.js:258:43
    at /Users/xxx/Documents/workspace/xxx/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at /Users/xxx/Documents/workspace/xxx/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/xxx/Documents/workspace/xxx/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/Users/xxx/Documents/workspace/xxx/node_modules/gensync/index.js:254:32)
 @ ./index.web.js 3:0-28 5:36-39
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./index.web.js
```
More details:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 2020-4-19 22:16:59                                            │
│  $ rnv                                                                       │
├──────────────────────────────────────────────────────────────────────────────┤
│  Project Name: xxx                                                           │
│  Project Version: 0.1.0                                                      │
│  App Config: blank                                                           │
│  Workspace: rnv                                                              │
│  Supported Platforms: androidtv, tizen, web, webos                           │
│  Env Info: darwin | x64 | node v12.16.2 | rnv v0.28.21                       │
│  Build Scheme: true                                                          │
├──────────────────────────────────────────────────────────────────────────────┤

```

**Comment by pavjacko** [comment]
@cereigido  this is fixed in upcoming version for now can you add this to your package.json 
```
"resolutions": {
        "@babel/preset-env": "7.8.7"
    },
```

**Comment by benz0is** [comment]
Hey I get the same issue , yet your solutions doesnt work for me :/ I edited the package.json file and wrote the
  "devDependencies": {
        "@babel/preset-env": "7.8.7",
But I still get the same problem

**Comment by TheDuc** [comment]
have you also added the "resolutions" part to your package.json?
```
{
    "name": "packagename",
    "version": "0.1.0",
    "dependencies": {
        (...)
    },
    "devDependencies": {
        (...)
        "@babel/preset-env": "^7.8.7"
    },
    "resolutions": {
        "@babel/preset-env": "^7.8.7"
    }
}

```

**Comment by benz0is** [comment]
I added it , still does not work :/

**Comment by cereigido** [comment]
It worked, thanks a lot. 

@benz0is, you also have to install this dependency.

**Comment by benz0is** [comment]
Now I get this error. Btw I have quite a few of the package.json files, which one should I choose?

│ �  $ rnv build -p web - ERRROR! loadFile: C:\Users\user\seal\package.json :: SyntaxError: Unexpected token { in JSON at position 1531
│ �  $ rnv build -p web - ERRROR! Cannot read property 'devDependencies' of undefined
TypeError: Cannot read property 'devDependencies' of undefined
    at devDependencies (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\src\templateTools\index.js:62:37)
    at new Promise (<anonymous>)
    at checkIfTemplateInstalled (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\src\templateTools\index.js:41:46)
    at _startBuilder$ (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\src\cli\index.js:322:11)
    at tryCatch (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:97:21)
    at tryCatch (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:45:40)
    at invoke (C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:135:20)
    at C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\regenerator-runtime\runtime.js:145:13
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

**Comment by elmpp** [comment]
try running `rnv build -Rp web`

**Comment by benz0is** [comment]
I just did that and I got this error: ( btw which package.json file should I edit ? )
│ �  $ rnv build -Rp web - ERRROR! COMMAND:

npx cross-env PLATFORM=web NODE_ENV=production  node C:\Users\user\AppData\Roaming\npm\node_modules\rnv\node_modules\webpack\bin\webpack.js -p --config ./platformBuilds/helloWorld_web/webpack.config.js

FAILED with ERROR:

[133] ./src/app/index.web.js 3.28 KiB {2} [built] [failed] [1 error]
[337] ./index.web.js 167 bytes {2} [built]
 + 339 hidden modules
ERROR in ./src/app/index.web.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/preset-env' from 'C:\Users\user\seal'
 at Function.resolveSync [as sync] (C:\Users\user\seal\node_modules\resolve\lib\sync.js:83:15)
 at resolveStandardizedName (C:\Users\user\seal\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
 at resolvePreset (C:\Users\user\seal\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
 at loadPreset (C:\Users\user\seal\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
 at createDescriptor (C:\Users\user\seal\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
│                                                                              │

**Comment by JoaoCEAlmeida** [comment]
@pavjacko worked for me using yarn.

If you're still using npm I think you need to run "npx npm-force-resolutions" before "npm install".
Check this link: https://stackoverflow.com/questions/60780664/could-not-find-plugin-proposal-numeric-separator

**Comment by benz0is** [comment]
Okay now I get a new error lol :
FAILED with ERROR:

ERROR in ./platformAssets/runtime/fonts.js 3:55
Module parse failed: Bad character escape sequence (3:55)
You may need an appropriate loader to handle this file type.
| export default [{
| fontFamily: 'AntDesign',
> file: require('C:\Users\user\seal\appConfigs\base\fonts\AntDesign.ttf'),
│
Pleasee help me. Thanks

**Comment by JoaoCEAlmeida** [comment]
@benz0is I'm getting the same error with my project fonts, still trying to fix it.

Also i'm getting this one: "ERROR in ./node_modules/renative/src/Button/index.web.js
Module not found: Error: Can't resolve '@reach/router'"

**Comment by benz0is** [comment]
@JoaoCEAlmeida if you find an answer , write it here , thanks!

**Comment by benz0is** [comment]
@JoaoCEAlmeida  I found the solution , just delete your fonts folder and it should work

**Comment by JoaoCEAlmeida** [comment]
@benz0is But I need the fonts in my project.
